version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    labels:
      - "ci/cd"
      - "security"
    reviewers:
      - "Guardianangelcore"
    commit-message:
      prefix: "ci"