/* Copyright © 2026 Guardian Angel Sovereign Foundation (DAO). All Rights Reserved. This source code and its logic are the sole property of the Foundation. Unauthorized duplication, modification, or distribution is strictly prohibited. */
// TERMS OF SERVICE — public page (reachable without login, linked from registration)
import React from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { C, S, R } from '@/src/theme';
import { LEGAL_VERSION as VERSION, LEGAL_EFFECTIVE as EFFECTIVE } from '@/src/legal';

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <View style={st.section}>
      <Text style={st.secTitle}>{n}. {title}</Text>
      {children}
    </View>
  );
}
const P = ({ children }: { children: React.ReactNode }) => <Text style={st.p}>{children}</Text>;
const B = ({ children }: { children: React.ReactNode }) => <Text style={st.bullet}>•  {children}</Text>;

export default function TermsOfService() {
  const router = useRouter();
  return (
    <SafeAreaView testID="tos-screen" style={st.root} edges={['top']}>
      <View style={st.header}>
        <Pressable testID="tos-back" onPress={() => router.back()} hitSlop={12}>
          <Ionicons name="chevron-back" size={26} color={C.fg} />
        </Pressable>
        <Text style={st.title}>TERMS OF SERVICE</Text>
        <View style={{ width: 26 }} />
      </View>
      <ScrollView contentContainerStyle={{ padding: S.lg, paddingBottom: 80 }}>
        <Text style={st.meta}>Version {VERSION} · Effective {EFFECTIVE}</Text>
        <Text style={st.meta}>Guardian Angel Sovereign Foundation (DAO) · guardian.angel.core@proton.me</Text>

        {/* MEDICAL DISCLAIMER — the single most important clause */}
        <View testID="tos-medical-disclaimer" style={st.discBox}>
          <View style={st.discHead}>
            <Ionicons name="medkit-outline" size={18} color={C.brand} />
            <Text style={st.discTitle}>MEDICAL DISCLAIMER</Text>
          </View>
          <Text style={st.discText}>
            Guardian Angel OS is NOT a medical device. It does NOT replace professional
            medical care, diagnosis, or treatment. Always consult a licensed physician
            before making any health decision. In an emergency, call your local emergency
            number (112 / 911) immediately.
          </Text>
        </View>

        <Section n="1" title="ACCEPTANCE OF TERMS">
          <P>By creating an account or using Guardian Angel OS ("the Service"), you agree to
            these Terms of Service and our Privacy Policy. If you do not agree, do not use
            the Service.</P>
        </Section>

        <Section n="2" title="THE SERVICE">
          <P>Guardian Angel OS is a personal health and family-safety companion. It provides
            informational tools such as health records ("Life Card"), AI assistance (Jarvis),
            document scanning, family alerts, and legacy planning.</P>
          <B>All AI-generated content is informational only and is watermarked in accordance
            with EU AI Act Article 50 ("AI Content · Sovereign Protocol").</B>
          <B>The Service does not provide medical, legal, financial, or tax advice.</B>
        </Section>

        <Section n="3" title="EMERGENCY & SAFETY FEATURES">
          <P>SOS buttons, fall detection, Crisis HUD, Bio-Beacon, and similar features are
            best-effort convenience aids. They depend on your device, sensors, battery, and
            network coverage and may fail or trigger falsely.</P>
          <B>Never rely on the Service as your only means of summoning help.</B>
          <B>Documents generated by the Service (e.g. testament drafts) are templates — have
            them reviewed by a qualified professional before use.</B>
        </Section>

        <Section n="4" title="YOUR ACCOUNT">
          <P>You must provide accurate information and keep your credentials secure. You are
            responsible for all activity under your account. You must be at least 16 years
            old (or the age of digital consent in your country) to create an account; younger
            children may only be represented through a parent's account (child Life Cards).</P>
        </Section>

        <Section n="5" title="ACCEPTABLE USE">
          <B>Do not misuse emergency features (false SOS alerts).</B>
          <B>Do not upload unlawful content or content that violates others' rights.</B>
          <B>Do not attempt to breach, probe, or reverse-engineer the Service.</B>
        </Section>

        <Section n="6" title="SUBSCRIPTIONS & GA-T TOKENS">
          <P>Some features require a paid tier (Guardian / Sentinel / Archangel). Prices and
            billing terms are shown at checkout. GA-T is an internal utility token used
            inside the Service; it is not money, not an investment, and confers no financial
            rights.</P>
        </Section>

        <Section n="7" title="INTELLECTUAL PROPERTY">
          <P>The Service, its design, and its logic are the property of the Guardian Angel
            Sovereign Foundation (DAO). You retain all rights to the personal content you
            store in the Service.</P>
        </Section>

        <Section n="8" title="LIMITATION OF LIABILITY">
          <P>To the maximum extent permitted by law, the Foundation is not liable for
            indirect, incidental, or consequential damages, including harm arising from
            reliance on AI outputs, missed alerts, or service interruptions. Nothing in
            these terms limits liability that cannot be limited by law.</P>
        </Section>

        <Section n="9" title="TERMINATION">
          <P>You may delete your account at any time. We may suspend accounts that violate
            these terms. Upon deletion, your data is removed as described in the Privacy
            Policy.</P>
        </Section>

        <Section n="10" title="CHANGES & GOVERNING LAW">
          <P>We may update these terms; material changes will be announced in the app and
            require re-acceptance. These terms are governed by the laws of the European
            Union and your country of residence where mandatory consumer law applies.</P>
        </Section>

        <Pressable testID="tos-privacy-link" onPress={() => router.push('/privacy-policy')} style={st.linkBtn}>
          <Ionicons name="shield-checkmark-outline" size={16} color={C.brand} />
          <Text style={st.linkBtnText}>READ THE PRIVACY POLICY</Text>
        </Pressable>

        <Text style={st.footer}>EU AI ACT ART. 50 · AI OUTPUTS ARE INFORMATIONAL ONLY · © 2026 GUARDIAN ANGEL SOVEREIGN FOUNDATION (DAO)</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const st = StyleSheet.create({
  root: { flex: 1, backgroundColor: C.bg },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: S.lg, paddingVertical: S.md },
  title: { color: C.fg, fontWeight: '900', letterSpacing: 2, fontSize: 14 },
  meta: { color: C.info, fontSize: 10.5, letterSpacing: 0.5, marginBottom: 4 },
  discBox: { borderWidth: 2, borderColor: C.brand, backgroundColor: 'rgba(212,175,55,0.08)', borderRadius: R.md, padding: S.lg, marginTop: S.md },
  discHead: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  discTitle: { color: C.brand, fontWeight: '900', fontSize: 12, letterSpacing: 2 },
  discText: { color: C.fg, fontSize: 13, lineHeight: 20, fontWeight: '600' },
  section: { marginTop: S.xl },
  secTitle: { color: C.brand, fontWeight: '900', fontSize: 11.5, letterSpacing: 1.5, marginBottom: 6 },
  p: { color: C.fg, fontSize: 13, lineHeight: 20, marginBottom: 6 },
  bullet: { color: C.onS3, fontSize: 12.5, lineHeight: 19, marginBottom: 4, paddingLeft: 4 },
  linkBtn: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: C.brand, borderRadius: R.sm, minHeight: 48, marginTop: S.xl },
  linkBtnText: { color: C.brand, fontWeight: '900', fontSize: 11, letterSpacing: 1.5 },
  footer: { textAlign: 'center', color: C.info, fontSize: 8.5, letterSpacing: 1, marginTop: S.xl, lineHeight: 13 },
});
